medicines::sitemaps::MedSiteMap
float medicines.sitemaps.MedSiteMap::priority
str medicines.sitemaps.MedSiteMap::changefreq
medicines.sitemaps.MedSiteMap.items(self)
Referenced by cart.models.Order.as_json, cart.models.Order.order_now, cart.models.Order.order_total.
medicines.sitemaps.MedSiteMap.location(self, obj)