medical::sitemaps::StaticSitemap
str medical.sitemaps.StaticSitemap::changeFreq
int medical.sitemaps.StaticSitemap::priority
medical.sitemaps.StaticSitemap.items(self)
Referenced by cart.models.Order.as_json, cart.models.Order.order_now, cart.models.Order.order_total.
medical.sitemaps.StaticSitemap.location(self, page)