accounts::sitemaps::AccountSiteMap
int accounts.sitemaps.AccountSiteMap::priority
str accounts.sitemaps.AccountSiteMap::changeFreq
accounts.sitemaps.AccountSiteMap.items(self)
Referenced by cart.models.Order.as_json, cart.models.Order.order_now, cart.models.Order.order_total.
accounts.sitemaps.AccountSiteMap.location(self, item)