accounts::sitemaps::AllAuthSitemap
int accounts.sitemaps.AllAuthSitemap::priority
str accounts.sitemaps.AllAuthSitemap::changeFreq
accounts.sitemaps.AllAuthSitemap.items(self)
Referenced by cart.models.Order.as_json, cart.models.Order.order_now, cart.models.Order.order_total.
accounts.sitemaps.AllAuthSitemap.location(self, item)