# Generated by Django 3.1 on 2020-08-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='landmark',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
