# Generated by Django 3.1.8 on 2021-04-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20200831_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='postOrder',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
