# Generated by Django 3.1 on 2020-08-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medcat',
            options={'verbose_name': 'Medicine Category'},
        ),
        migrations.AlterField(
            model_name='medicine',
            name='quantity',
            field=models.PositiveBigIntegerField(),
        ),
    ]
