# Generated by Django 3.1 on 2020-08-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_medicine_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='slug',
            field=models.SlugField(default='>bmmid.ogoihlCd', unique=True),
        ),
    ]
