# Generated by Django 3.1 on 2020-08-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0005_auto_20200828_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='slug',
            field=models.SlugField(default='i<d.sla.eaDmdll', unique=True),
        ),
    ]
