# Generated by Django 3.1 on 2020-08-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0006_auto_20200828_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='slug',
            field=models.SlugField(default='rdbFsdjdii.Cd.e', unique=True),
        ),
    ]
