# Generated by Django 3.1 on 2020-08-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0008_auto_20200828_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='slug',
            field=models.SlugField(default='deldfililble.dF', unique=True),
        ),
    ]
