# Generated by Django 3.1 on 2020-08-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0009_auto_20200828_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='slug',
            field=models.SlugField(default='lme.ndiahe<jabl', unique=True),
        ),
    ]
