# Generated by Django 3.1 on 2020-08-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0013_auto_20200830_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='slug',
            field=models.SlugField(default='jneb>dFlbgmD.dl', unique=True),
        ),
    ]
