# Generated by Django 3.1 on 2020-08-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0014_auto_20200830_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='slug',
            field=models.SlugField(default='nnsl.fsmomlea.D', unique=True),
        ),
    ]
