# Generated by Django 3.1 on 2020-08-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0017_auto_20200830_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='slug',
            field=models.SlugField(default='.olN.oeDodelfjg', unique=True),
        ),
    ]
