# Generated by Django 3.1 on 2020-08-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0022_auto_20200830_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='slug',
            field=models.SlugField(default='di<DlNmddd..e.e', unique=True),
        ),
    ]
