# Generated by Django 3.1 on 2020-08-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0025_auto_20200830_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='slug',
            field=models.SlugField(default='iboseolnsinag.e', unique=True),
        ),
    ]
