# Generated by Django 3.1 on 2020-08-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0026_auto_20200831_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='slug',
            field=models.SlugField(default='ger<s<Cmls..a.e', unique=True),
        ),
    ]
