# Generated by Django 3.1 on 2020-08-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0027_auto_20200831_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='slug',
            field=models.SlugField(default='Noi.eolecdaFjel', unique=True),
        ),
    ]
