# Generated by Django 3.1 on 2020-08-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0029_auto_20200831_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='slug',
            field=models.SlugField(default='dasidebFmoNmigo', unique=True),
        ),
    ]
