# Generated by Django 3.1 on 2020-08-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0030_auto_20200831_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='slug',
            field=models.SlugField(default='.jFlfomescm<.i.', unique=True),
        ),
    ]
