# Generated by Django 3.1 on 2020-08-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0031_auto_20200831_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='slug',
            field=models.SlugField(default='idsgfladib.lbig', unique=True),
        ),
    ]
