# Generated by Django 3.1 on 2020-09-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0033_auto_20200901_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='slug',
            field=models.SlugField(default='.eeCenaoFjjDrd.', unique=True),
        ),
    ]
