# Generated by Django 3.1 on 2020-09-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0036_auto_20200908_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='slug',
            field=models.SlugField(default='di>nsegbf.de.ai', unique=True),
        ),
    ]
