# Generated by Django 3.1 on 2020-09-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0038_auto_20200908_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['-price']},
        ),
        migrations.AlterField(
            model_name='medicine',
            name='slug',
            field=models.SlugField(default='mdooid.<g.amefa', unique=True),
        ),
    ]
