# Generated by Django 3.1 on 2020-09-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0039_auto_20200910_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='slug',
            field=models.SlugField(default='demg.<rcos.e>Fd', unique=True),
        ),
    ]
