# Generated by Django 3.1 on 2021-01-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0040_auto_20200915_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='slug',
            field=models.SlugField(default='.i.i..oejd.dmmF', unique=True),
        ),
    ]
