# Generated by Django 3.1 on 2021-04-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0041_auto_20210122_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='slug',
            field=models.SlugField(default='miegdFamosod.mi', unique=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='thumb_content_type',
            field=models.CharField(blank=True, default='image/png', help_text='MIMEType for thumbnail', max_length=256, null=True),
        ),
    ]
